// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0iXbWf2AvE37yEFbD2QsbIoPRpTD8gBY',
    appId: '1:589507110646:web:b5365e67789392c6bb6ed7',
    messagingSenderId: '589507110646',
    projectId: 'booktalk-d7784',
    authDomain: 'booktalk-d7784.firebaseapp.com',
    storageBucket: 'booktalk-d7784.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGRVvdZ0Q0aP_Cq64CCPxnKgonSak7i34',
    appId: '1:589507110646:android:558b195ce90546ffbb6ed7',
    messagingSenderId: '589507110646',
    projectId: 'booktalk-d7784',
    storageBucket: 'booktalk-d7784.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0iXbWf2AvE37yEFbD2QsbIoPRpTD8gBY',
    appId: '1:589507110646:web:c8b7c1715a63fd91bb6ed7',
    messagingSenderId: '589507110646',
    projectId: 'booktalk-d7784',
    authDomain: 'booktalk-d7784.firebaseapp.com',
    storageBucket: 'booktalk-d7784.appspot.com',
  );
}
